### ISSUE TITLE
Deadlock if errors occur during startup

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#13]
"AWT-EventQueue-0" #68 prio=6 os_prio=0 tid=0x00007ff7a45f1800 nid=0x382a waiting for monitor entry [0x00007ff77d8a3000] 
   java.lang.Thread.State: BLOCKED (on object monitor) 
at dagger.internal.Linker$SingletonBinding.get(Linker.java:362) 
- waiting to lock <0x000000076e22aed0> (a dagger.internal.Linker$SingletonBinding) 
at com.dmdirc.addons.ui_swing.components.statusbar.ErrorPanel.isReady(ErrorPanel.java:170) 
at com.dmdirc.logger.ErrorManager.fireErrorAdded(ErrorManager.java:403) 
at com.dmdirc.logger.ErrorManager.addError(ErrorManager.java:236) 
at com.dmdirc.logger.ErrorManager.addError(ErrorManager.java:206) 
at com.dmdirc.logger.ErrorManager.addError(ErrorManager.java:173) 
at com.dmdirc.logger.Logger.appError(Logger.java:82) 
at com.dmdirc.logger.DMDircExceptionHandler.uncaughtException(DMDircExceptionHandler.java:36) 
at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057) 
at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223) 
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215) 
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 

"main" #1 prio=5 os_prio=0 tid=0x00007ff7a4009800 nid=0x37de in Object.wait() [0x00007ff7aafdc000] 
   java.lang.Thread.State: WAITING (on object monitor) 
at java.lang.Object.wait(Native Method) 
- waiting on <0x000000076d952eb8> (a java.awt.EventQueue$1AWTInvocationLock) 
at java.lang.Object.wait(Object.java:502) 
at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294) 
- locked <0x000000076d952eb8> (a java.awt.EventQueue$1AWTInvocationLock) 
at java.awt.EventQueue.invokeAndWait(EventQueue.java:1275) 
at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348) 
at com.dmdirc.addons.ui_swing.UIUtilities.invokeAndWait(UIUtilities.java:228) 
at com.dmdirc.addons.ui_swing.injection.SwingModule.getSwingStatusBar(SwingModule.java:187) 
at com.dmdirc.addons.ui_swing.injection.SwingModule$$ModuleAdapter$GetSwingStatusBarProvidesAdapter.get(SwingModule$$ModuleAdapter.java:429) 
at com.dmdirc.addons.ui_swing.injection.SwingModule$$ModuleAdapter$GetSwingStatusBarProvidesAdapter.get(SwingModule$$ModuleAdapter.java:381) 
at dagger.internal.Linker$SingletonBinding.get(Linker.java:364) 
- locked <0x000000076e22aed0> (a dagger.internal.Linker$SingletonBinding) 
at com.dmdirc.addons.ui_swing.SwingManager.load(SwingManager.java:161) 
at com.dmdirc.addons.ui_swing.SwingController.onLoad(SwingController.java:89) 
at com.dmdirc.plugins.PluginInfo.loadClass(PluginInfo.java:756) 
at com.dmdirc.plugins.PluginInfo.loadPlugin(PluginInfo.java:630) 
at com.dmdirc.plugins.PluginInfo.activateServices(PluginInfo.java:441) 
at com.dmdirc.plugins.Service.activate(Service.java:141) 
at com.dmdirc.Main.loadUIs(Main.java:263) 
at com.dmdirc.Main.init(Main.java:187) 
at com.dmdirc.Main.main(Main.java:167)

**Comment by csmith** [comment]
Don't think this can happen now everything is eventy.
