### ISSUE TITLE
Deadlock connecting to server that fails SSL validation

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#607]
Trying to connect to a bouncer (with an outdated, untrusted cert).

The SSL validation dialog sort of appears but doesn't fully render:

![dmdirc-ssl](https://cloud.githubusercontent.com/assets/189133/12650100/6b171cf8-c5d9-11e5-982d-781d3ed886c9.png)

Relevant threads seem to be:

```
"Message dispatcher" #46 daemon prio=5 os_prio=0 tid=0x00007f34ac003000 nid=0x14819 in Object.wait() [0x00007f34cd527000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000846c6f10> (a java.awt.EventQueue$1AWTInvocationLock)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1313)
	- locked <0x00000000846c6f10> (a java.awt.EventQueue$1AWTInvocationLock)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.dmdirc.addons.ui_swing.UIUtilities.invokeAndWait(UIUtilities.java:207)
	at com.dmdirc.addons.ui_swing.EdtHandlerInvocation.invokeHandler(EdtHandlerInvocation.java:53)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:41)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:73)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:46)
	at net.engio.mbassy.bus.MBassador.publish(MBassador.java:36)
	at com.dmdirc.util.ChildEventBusManager$EventPropagator.handleEvent(ChildEventBusManager.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:41)
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:73)
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:46)
	at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:61)
	at java.lang.Thread.run(Thread.java:745)

"Thread-4" #40 prio=5 os_prio=0 tid=0x00007f34c800d800 nid=0x14802 waiting for monitor entry [0x00007f34ea27d000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.awt.Component$AccessibleAWTComponent.getLocationOnScreen(Component.java:9490)
	- waiting to lock <0x0000000083c66d70> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent$AccessibleJComponent.getLocationOnScreen(JComponent.java:3663)
	at javax.swing.text.JTextComponent$AccessibleJTextComponent.<init>(JTextComponent.java:2516)
	at javax.swing.JEditorPane$AccessibleJEditorPane.<init>(JEditorPane.java:1643)
	at javax.swing.JEditorPane$JEditorPaneAccessibleHypertextSupport.<init>(JEditorPane.java:1970)
	at javax.swing.JEditorPane$AccessibleJEditorPaneHTML.getAccessibleText(JEditorPane.java:1702)


"AWT-EventQueue-1" #29 prio=6 os_prio=0 tid=0x00007f3574785000 nid=0x14801 runnable [0x00007f34ea37c000]
   java.lang.Thread.State: RUNNABLE
	at com.sun.java.swing.plaf.gtk.GTKStyle.nativeGetClassValue(Native Method)
	at com.sun.java.swing.plaf.gtk.GTKStyle.getClassSpecificValue(GTKStyle.java:603)
	- locked <0x000000008392b5a8> (a java.lang.Object)
	at com.sun.java.swing.plaf.gtk.GTKStyle.getClassSpecificIntValue(GTKStyle.java:620)
	at com.sun.java.swing.plaf.gtk.GTKStyle.get(GTKStyle.java:791)
	at javax.swing.plaf.synth.SynthArrowButton$SynthArrowButtonUI.getPreferredSize(SynthArrowButton.java:106)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutVScrollbar(BasicScrollBarUI.java:662)
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(BasicScrollBarUI.java:866)
	at javax.swing.plaf.basic.BasicScrollBarUI$ModelListener.stateChanged(BasicScrollBarUI.java:1054)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
	at javax.swing.JScrollBar.setValues(JScrollBar.java:623)
	at javax.swing.plaf.basic.BasicScrollPaneUI.syncScrollPaneWithViewport(BasicScrollPaneUI.java:285)
	at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1039)
	at javax.swing.JViewport.fireStateChanged(JViewport.java:1369)
	at javax.swing.JViewport.setViewSize(JViewport.java:1021)
	at javax.swing.ViewportLayout.layoutContainer(ViewportLayout.java:201)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	- locked <0x0000000083c66d70> (a java.awt.Component$AWTTreeLock)
	at java.awt.Window.dispatchEventImpl(Window.java:2748)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.dmdirc.addons.ui_swing.DMDircEventQueue.dispatchEvent(DMDircEventQueue.java:68)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by csmith** [comment]
Might not actually be a deadlock as such - it seems like `nativeGetClassValue` is just not returning...

**Comment by csmith** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798131 maybe

**Comment by csmith** [comment]
IDEA does the same on that VM, so pretty sure it's a JVM bug.
