### ISSUE TITLE
Error during invocation of message handler. Message handler threw exception

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#630]
Repro steps:

1) /dcc chat foo
2) close the root DCC window

https://sentry.dmdirc.com/sentry/dmdirc/issues/5/

```
IllegalStateException: None
    at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
    at com.dmdirc.ui.WindowManager.removeWindow(WindowManager.java:242)
    at com.dmdirc.ui.WindowManager.frameClosing(WindowManager.java:368)
    at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
    at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
...
(62 additional frame(s) were not displayed)
```

**Comment by csmith** [comment]
I suspect the DCC window isn't closing its children, and it's meant to (or something along those lines).
