### ISSUE TITLE
ServerManager needs updating

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#665]
I'm pretty sure its handler to remove servers on close no longer works.

Worth taking a look to see if servers can be replaced with connections as well.

**Comment by greboid** [comment]
Error during invocation of message handler. Message handler threw exception
java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.dmdirc.ui.WindowManager.removeWindow(WindowManager.java:260)
        at com.dmdirc.ui.WindowManager.frameClosing(WindowManager.java:414)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
        at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
        at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:41)
        at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:71)
        at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:46)
        at net.engio.mbassy.bus.MBassador.publish(MBassador.java:70)
        at com.dmdirc.FrameContainer.close(FrameContainer.java:189)
        at com.dmdirc.ServerManager.closeAll(ServerManager.java:155)
        at com.dmdirc.addons.ui_swing.QuitWorker.doInBackground(QuitWorker.java:75)
        at com.dmdirc.addons.ui_swing.QuitWorker.doInBackground(QuitWorker.java:38)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
