### ISSUE TITLE
NPE not reportable

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#681]
Got this error when trying to use /topic, the error reporter says it's not reportable:

```
java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at com.dmdirc.addons.ui_swing.components.SupplierLoggingSwingWorker.done(SupplierLoggingSwingWorker.java:97)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.dmdirc.addons.ui_swing.DMDircEventQueue.dispatchEvent(DMDircEventQueue.java:68)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.util.Optional.orElseGet(Unknown Source)
	at com.dmdirc.commandparser.commands.channel.ShowTopic.execute(ShowTopic.java:80)
	at com.dmdirc.commandparser.parsers.ChannelCommandParser.executeCommand(ChannelCommandParser.java:88)
	at com.dmdirc.commandparser.parsers.CommandParser.parseCommand(CommandParser.java:148)
	at com.dmdirc.commandparser.parsers.CommandParser.parseCommand(CommandParser.java:272)
	at com.dmdirc.ui.input.InputHandler.enterPressed(InputHandler.java:588)
	at com.dmdirc.addons.ui_swing.components.inputfields.SwingInputHandler$5.lambda$null$162(SwingInputHandler.java:208)
	at com.dmdirc.addons.ui_swing.components.RunnableLoggingSwingWorker.lambda$new$145(RunnableLoggingSwingWorker.java:63)
	at com.dmdirc.addons.ui_swing.components.SupplierLoggingSwingWorker.doInBackground(SupplierLoggingSwingWorker.java:86)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by csmith** [comment]
Fixed in DMDirc/Plugins#471
