### ISSUE TITLE
Exception in Processor. [com.dmdirc.parser.irc.processors.ProcessJoin]: null

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#715]
https://sentry.dmdirc.com/sentry/dmdirc/issues/33/

```
NullPointerException: None
    at com.dmdirc.parser.irc.processors.ProcessJoin.process(ProcessJoin.java:198)
    at com.dmdirc.parser.irc.ProcessingManager.process(ProcessingManager.java:155)
    at com.dmdirc.parser.irc.IRCParser.processLine(IRCParser.java:1191)
    at com.dmdirc.parser.irc.IRCParser.run(IRCParser.java:866)
    at com.dmdirc.parser.common.ThreadedParser$$Lambda$209/756553967.run
...
(1 additional frame(s) were not displayed)
```

**Comment by greboid** [comment]
Last line received: :server 473 Nickname #Channel :Cannot join channel, you must be invited (+i)

**Comment by greboid** [comment]
parser version: 0.8-263-gd82ee6f
