### ISSUE TITLE
Feedback dialog fails to open

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#761]
https://sentry.dmdirc.com/sentry/dmdirc/issues/45/

```
IllegalArgumentException: Not valid in vertical contexts: 'label'
    at net.miginfocom.layout.UnitValue.parseUnitString
    at net.miginfocom.layout.UnitValue.<init>
    at net.miginfocom.layout.UnitValue.<init>
...
(46 additional frame(s) were not displayed)

IllegalArgumentException: Malformed UnitValue: 'label'
    at net.miginfocom.layout.ConstraintParser.parseUnitValue
    at net.miginfocom.layout.ConstraintParser.parseUnitValueOrAlign
...
(43 additional frame(s) were not displayed)

IllegalArgumentException: Error parsing Constraint: 'aligny label'
    at net.miginfocom.layout.ConstraintParser.parseComponentConstraint
    at net.miginfocom.swing.MigLayout.setComponentConstraintsImpl
    at net.miginfocom.swing.MigLayout.addLayoutComponent
    at com.dmdirc.addons.ui_swing.dialogs.feedback.FeedbackDialog.<init>(FeedbackDialog.java:88)
    at com.dmdirc.addons.ui_swing.dialogs.feedback.FeedbackDialog$$InjectAdapter.get(FeedbackDialog$$InjectAdapter.java:71)
...
(41 additional frame(s) were not displayed)
```

**Comment by csmith** [comment]
Fixed in DMDirc/Plugins/pull/516
