### ISSUE TITLE
Deadlock on start

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#79]
```
"main" #1 prio=5 os_prio=0 tid=0x00007f28dc00a000 nid=0xe13 waiting for monitor entry [0x00007f28e4414000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.awt.AppContext$3.run(AppContext.java:316)
	- waiting to lock <0x000000076d088e10> (a sun.awt.AppContext$GetAppContextLock)
	at sun.awt.AppContext$3.run(AppContext.java:302)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.getAppContext(AppContext.java:301)
	at sun.awt.AppContext$6.getAppletContext(AppContext.java:867)
	at java.util.logging.LogManager.getUserContext(LogManager.java:508)
	- locked <0x000000076d088f20> (a sun.awt.AppContext$6)
	at java.util.logging.LogManager.addLogger(LogManager.java:1161)
	at java.util.logging.LogManager.demandSystemLogger(LogManager.java:592)
	at java.util.logging.Logger.getPlatformLogger(Logger.java:573)
	at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
	at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:602)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:597)
	at sun.util.logging.PlatformLogger.<init>(PlatformLogger.java:239)
	at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:198)
	- locked <0x00000006c639c870> (a java.lang.Class for sun.util.logging.PlatformLogger)
	at java.awt.EventQueue.<clinit>(EventQueue.java:185)
	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
	at com.dmdirc.addons.ui_swing.UIUtilities.invokeAndWait(UIUtilities.java:224)
	at com.dmdirc.addons.ui_swing.injection.SwingModule.getMainFrame(SwingModule.java:144)
	at com.dmdirc.addons.ui_swing.injection.SwingModule$$ModuleAdapter$GetMainFrameProvidesAdapter.get(SwingModule$$ModuleAdapter.java:217)
	at com.dmdirc.addons.ui_swing.injection.SwingModule$$ModuleAdapter$GetMainFrameProvidesAdapter.get(SwingModule$$ModuleAdapter.java:163)
	at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
	- locked <0x000000076de0c750> (a dagger.internal.Linker$SingletonBinding)
	at com.dmdirc.addons.ui_swing.injection.SwingModule$$ModuleAdapter$GetActiveFrameManagerProvidesAdapter.get(SwingModule$$ModuleAdapter.java:367)
	at com.dmdirc.addons.ui_swing.injection.SwingModule$$ModuleAdapter$GetActiveFrameManagerProvidesAdapter.get(SwingModule$$ModuleAdapter.java:331)
	at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
	- locked <0x000000076de1af00> (a dagger.internal.Linker$SingletonBinding)
	at com.dmdirc.addons.ui_swing.framemanager.ctrltab.CtrlTabWindowManager$$InjectAdapter.get(CtrlTabWindowManager$$InjectAdapter.java:64)
	at com.dmdirc.addons.ui_swing.framemanager.ctrltab.CtrlTabWindowManager$$InjectAdapter.get(CtrlTabWindowManager$$InjectAdapter.java:19)
	at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
	- locked <0x000000076ccbdb58> (a dagger.internal.Linker$SingletonBinding)
	at com.dmdirc.addons.ui_swing.SwingManager$$InjectAdapter.get(SwingManager$$InjectAdapter.java:100)
	at com.dmdirc.addons.ui_swing.SwingManager$$InjectAdapter.get(SwingManager$$InjectAdapter.java:19)
	at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
	- locked <0x000000076de1a3d8> (a dagger.internal.Linker$SingletonBinding)
	at dagger.ObjectGraph$DaggerObjectGraph.get(ObjectGraph.java:272)
	at com.dmdirc.addons.ui_swing.SwingController.load(SwingController.java:73)
	at com.dmdirc.plugins.PluginInfo.loadClass(PluginInfo.java:752)
	at com.dmdirc.plugins.PluginInfo.loadPlugin(PluginInfo.java:627)
	at com.dmdirc.plugins.PluginInfo.activateServices(PluginInfo.java:442)
	at com.dmdirc.plugins.Service.activate(Service.java:141)
	at com.dmdirc.Main.loadUIs(Main.java:264)
	at com.dmdirc.Main.init(Main.java:188)
	at com.dmdirc.Main.main(Main.java:168)
```

```

"AWT-XAWT" #23 daemon prio=6 os_prio=0 tid=0x00007f28dc5fe000 nid=0xe33 in Object.wait() [0x00007f28ae177000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at sun.awt.SunToolkit.initEQ(SunToolkit.java:115)
	at sun.awt.SunToolkit.createNewAppContext(SunToolkit.java:298)
	at sun.awt.AppContext$2.run(AppContext.java:275)
	at sun.awt.AppContext$2.run(AppContext.java:264)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.initMainAppContext(AppContext.java:264)
	at sun.awt.AppContext.access$400(AppContext.java:133)
	at sun.awt.AppContext$3.run(AppContext.java:319)
	- locked <0x000000076d088e10> (a sun.awt.AppContext$GetAppContextLock)
	at sun.awt.AppContext$3.run(AppContext.java:302)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.getAppContext(AppContext.java:301)
	at java.awt.AWTKeyStroke.getCachedStroke(AWTKeyStroke.java:252)
	- locked <0x000000076d087630> (a java.lang.Class for java.awt.AWTKeyStroke)
	at java.awt.AWTKeyStroke.getAWTKeyStroke(AWTKeyStroke.java:391)
	at java.awt.KeyboardFocusManager.<clinit>(KeyboardFocusManager.java:332)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.awt.AWTAccessor.getKeyboardFocusManagerAccessor(AWTAccessor.java:877)
	at sun.awt.KeyboardFocusManagerPeerImpl.<clinit>(KeyboardFocusManagerPeerImpl.java:49)
	at sun.awt.X11.XToolkit.run(XToolkit.java:603)
	at sun.awt.X11.XToolkit.run(XToolkit.java:542)
	at java.lang.Thread.run(Thread.java:744)
```

Not really sure why that second thread isn't progressing...

**Comment by csmith** [comment]
Haven't seen recently.
