### ISSUE TITLE
Client keeps deadlocking on MacOS

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#790]
Maybe an issue with the JVM or MigLayout, rather than something we're doing?

```
"AppKit Thread" #20 daemon prio=5 os_prio=31 tid=0x00007fee120d7800 nid=0x307 waiting for monitor entry [0x00007fff577ec000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.awt.CGraphicsEnvironment.getScreenDevice(CGraphicsEnvironment.java:197)
	- waiting to lock <0x00000006c03f6e80> (a sun.awt.CGraphicsEnvironment)
	at sun.lwawt.macosx.CPlatformView.getGraphicsDevice(CPlatformView.java:161)
	at sun.lwawt.macosx.CPlatformWindow.getGraphicsDevice(CPlatformWindow.java:457)
	at sun.lwawt.LWWindowPeer.updateGraphicsDevice(LWWindowPeer.java:1036)
	at sun.lwawt.LWWindowPeer.notifyReshape(LWWindowPeer.java:637)
	at sun.lwawt.macosx.CPlatformWindow.deliverMoveResizeEvent(CPlatformWindow.java:956)


"AWT-EventQueue-0" #26 prio=6 os_prio=31 tid=0x00007fee158b6800 nid=0x11303 runnable [0x000070000b114000]
   java.lang.Thread.State: RUNNABLE
	at sun.java2d.opengl.CGLGraphicsConfig.nativeGetMaxTextureSize(Native Method)
	at sun.java2d.opengl.CGLGraphicsConfig.getConfig(CGLGraphicsConfig.java:150)
	at sun.awt.CGraphicsDevice.<init>(CGraphicsDevice.java:64)
	at sun.awt.CGraphicsEnvironment.initDevices(CGraphicsEnvironment.java:163)
	- locked <0x00000006c03f6e80> (a sun.awt.CGraphicsEnvironment)
	at sun.awt.CGraphicsEnvironment.getDefaultScreenDevice(CGraphicsEnvironment.java:181)
	- locked <0x00000006c03f6e80> (a sun.awt.CGraphicsEnvironment)
	at sun.lwawt.macosx.LWCToolkit.getScreenResolution(LWCToolkit.java:401)
	at net.miginfocom.swing.SwingComponentWrapper.getHorizontalScreenDPI(Unknown Source)
	at net.miginfocom.swing.SwingComponentWrapper.getPixelUnitFactor(Unknown Source)
	at net.miginfocom.layout.UnitValue.getPixelsExact(Unknown Source)
	at net.miginfocom.layout.UnitValue.getPixels(Unknown Source)
	at net.miginfocom.layout.BoundSize.getPixelSizes(Unknown Source)
	at net.miginfocom.layout.Grid.getRowGaps(Unknown Source)
	at net.miginfocom.layout.Grid.calcRowsOrColsSizes(Unknown Source)
	at net.miginfocom.layout.Grid.calcGridSizes(Unknown Source)
	at net.miginfocom.layout.Grid.checkSizeCalcs(Unknown Source)
	at net.miginfocom.layout.Grid.layoutImpl(Unknown Source)
	at net.miginfocom.layout.Grid.layout(Unknown Source)
	at net.miginfocom.swing.MigLayout.layoutContainer(Unknown Source)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:140)
	at javax.swing.plaf.basic.BasicTreeUI.paintRow(BasicTreeUI.java:1540)
	at javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1224)
	at javax.swing.plaf.metal.MetalTreeUI.paint(MetalTreeUI.java:169)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	- locked <0x00000006c02a6208> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.dmdirc.addons.ui_swing.DMDircEventQueue.dispatchEvent(DMDircEventQueue.java:63)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by csmith** [comment]
Looks like this is possibly https://bugs.openjdk.java.net/browse/JDK-8152683

Fixed in JDK9. Doubt we can work around it sanely.
