### ISSUE TITLE
Parser doesn't shutdown eventbus threads properly

### ISSUE THREAD

**Issue by ShaneMcC** [DMDirc/DMDirc#798]
```
[19:09:34] [shane@Xion:~]$ ps -T ux | grep -i DMDirc | wc -l
9833
[19:09:36] [shane@Xion:~]$ 
```
That's a little much, considering the default (at least on machines I have access to) is around 10k:

```
[19:12:18] [shane@ShanePC:~]$ cat /sys/fs/cgroup/pids/user.slice/user-1000.slice/pids.max
10813
[19:12:52] [shane@ShanePC:~]$ 
```

(This is the maximum number of threads allowed per user)

This causes fun problems for the user, such as not being able to open any new applications, applications crashing, shell processes failing to start (`fork failed: Resource temporarily unavailable`) etc.

Looks like we're creating a few new threads per minute:

```
USER       PID  SPID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
shane     2627 15528  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15532  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15537  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15543  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15548  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15553  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15558  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15564  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15574  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15578  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15583  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15588  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:00   0:00 java -jar DMDirc.jar
shane     2627 15599  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15604  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15630  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15679  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15684  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15688  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15694  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15699  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15755  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15763  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15857  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15862  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:01   0:00 java -jar DMDirc.jar
shane     2627 15874  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:02   0:00 java -jar DMDirc.jar
shane     2627 15878  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:02   0:00 java -jar DMDirc.jar
shane     2627 15883  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:02   0:00 java -jar DMDirc.jar
shane     2627 15890  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:02   0:00 java -jar DMDirc.jar
shane     2627 15895  0.0 10.7 19742424 1545400 pts/2 Sl+ 00:02   0:00 java -jar DMDirc.jar
...
shane     2627  6976  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  6980  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  6989  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  6995  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  6999  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  7004  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  7009  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  7015  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:57   0:00 java -jar DMDirc.jar
shane     2627  7029  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:58   0:00 java -jar DMDirc.jar
shane     2627  7041  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:58   0:00 java -jar DMDirc.jar
```

**Comment by ShaneMcC** [comment]
Unfortunately, my DMDirc crashed as I was raising this bug report, so I can't pull a thread dump from it just now.

Current running version has a much more respectable number of threads:

```
[19:26:34] [shane@Xion:~]$ ps -T ux | grep -i DMDirc | wc -l
73
[19:26:35] [shane@Xion:~]$ 
```

Which is close enough to what the thread dump shows:
```
"ForkJoinPool.commonPool-worker-2" #117 daemon prio=5 os_prio=0 tid=0x00007feb38001800 nid=0x6d24 waiting on condition [0x00007febe5ee7000]
"ForkJoinPool.commonPool-worker-1" #116 daemon prio=5 os_prio=0 tid=0x00007feb38003800 nid=0x6d23 waiting on condition [0x00007febe64eb000]
"SwingWorker-pool-43-thread-10" #115 daemon prio=5 os_prio=0 tid=0x00007feb7c1a0800 nid=0x6cf5 waiting on condition [0x00007febe62e9000]
"SwingWorker-pool-43-thread-9" #106 daemon prio=5 os_prio=0 tid=0x00007feb7c1a0000 nid=0x6b80 waiting on condition [0x00007febe61e8000]
"SwingWorker-pool-43-thread-8" #93 daemon prio=5 os_prio=0 tid=0x00007feb7c19d800 nid=0x6b00 waiting on condition [0x00007febedce6000]
"SwingWorker-pool-43-thread-7" #92 daemon prio=5 os_prio=0 tid=0x00007feb7c19c800 nid=0x6afe waiting on condition [0x00007febe65ec000]
"SwingWorker-pool-43-thread-6" #91 daemon prio=5 os_prio=0 tid=0x00007feb7c0c8000 nid=0x6afd waiting on condition [0x00007febed8e2000]
"SwingWorker-pool-43-thread-5" #90 daemon prio=5 os_prio=0 tid=0x00007feb7c100800 nid=0x6afb waiting on condition [0x00007febed9e3000]
"SwingWorker-pool-43-thread-4" #84 daemon prio=5 os_prio=0 tid=0x00007feb7c0fc800 nid=0x6ad2 waiting on condition [0x00007febe66ed000]
"Composition state timer-0" #83 prio=5 os_prio=0 tid=0x00007feb7c1bc000 nid=0x6ad0 waiting on condition [0x00007febedae4000]
"IRCParser pingTimer" #82 prio=5 os_prio=0 tid=0x00007feb54012000 nid=0x6ac9 in Object.wait() [0x00007febe67ee000]
"IRC Parser queue handler" #81 prio=5 os_prio=0 tid=0x00007feb5400d000 nid=0x6ac8 waiting on condition [0x00007febed177000]
"Parser - bnc.dataforce.org.uk" #80 prio=5 os_prio=0 tid=0x00007feb5c002800 nid=0x6ac5 runnable [0x00007fec06f02000]
"MsgDispatcher-0" #77 daemon prio=5 os_prio=0 tid=0x00007feb5c001800 nid=0x6ac2 waiting on condition [0x00007febecaf5000]
"Composition state timer-0" #76 prio=5 os_prio=0 tid=0x00007feb7c1bd800 nid=0x6ac0 waiting on condition [0x00007febe75f6000]
"server-timer-0" #75 prio=5 os_prio=0 tid=0x00007feb20002000 nid=0x6abf waiting on condition [0x00007febed7e1000]
"SwingWorker-pool-43-thread-3" #74 daemon prio=5 os_prio=0 tid=0x00007feb7c17e000 nid=0x6abd waiting on condition [0x00007febe6aef000]
"SwingWorker-pool-43-thread-2" #73 daemon prio=5 os_prio=0 tid=0x00007feb7c17c800 nid=0x6abc waiting on condition [0x00007febec9f4000]
"SwingWorker-pool-43-thread-1" #71 daemon prio=5 os_prio=0 tid=0x00007feb7c17b800 nid=0x6abb waiting on condition [0x00007febed6e0000]
"IRCParser pingTimer" #70 daemon prio=5 os_prio=0 tid=0x00007feb3000a000 nid=0x6aaa in Object.wait() [0x00007febe6df0000]
"IRCParser pingTimer" #69 daemon prio=5 os_prio=0 tid=0x00007feb28003800 nid=0x6aa9 in Object.wait() [0x00007febe6ef1000]
"IRCParser pingTimer" #68 daemon prio=5 os_prio=0 tid=0x00007feb34019000 nid=0x6aa8 in Object.wait() [0x00007febe6ff2000]
"IRC Parser queue handler" #67 daemon prio=5 os_prio=0 tid=0x00007feb28001000 nid=0x6aa7 waiting on condition [0x00007febe70f3000]
"IRC Parser queue handler" #66 daemon prio=5 os_prio=0 tid=0x00007feb30002800 nid=0x6aa6 waiting on condition [0x00007febe71f4000]
"IRC Parser queue handler" #65 daemon prio=5 os_prio=0 tid=0x00007feb3400c800 nid=0x6aa5 waiting on condition [0x00007febe72f5000]
"AsyncHandler-0" #64 daemon prio=5 os_prio=0 tid=0x00007feba0077800 nid=0x6aa3 waiting on condition [0x00007febedbe5000]
"MsgDispatcher-0" #60 daemon prio=5 os_prio=0 tid=0x00007feba0074000 nid=0x6a9f waiting on condition [0x00007febe77f8000]
"Parser - bnc.dataforce.org.uk" #59 daemon prio=5 os_prio=0 tid=0x00007feba0073000 nid=0x6a9e runnable [0x00007febe76f7000]
"MsgDispatcher-0" #56 daemon prio=5 os_prio=0 tid=0x00007feba006f800 nid=0x6a9b waiting on condition [0x00007febe78f9000]
"Parser - bnc.dataforce.org.uk" #55 daemon prio=5 os_prio=0 tid=0x00007feba006f000 nid=0x6a9a runnable [0x00007febe79fa000]
"MsgDispatcher-0" #52 daemon prio=5 os_prio=0 tid=0x00007feba006b000 nid=0x6a97 waiting on condition [0x00007febe7afb000]
"channelwho-0" #51 prio=5 os_prio=0 tid=0x00007feba0065000 nid=0x6a96 waiting on condition [0x00007febe7bfc000]
"Parser - bnc.dataforce.org.uk" #50 daemon prio=5 os_prio=0 tid=0x00007feba005d000 nid=0x6a95 runnable [0x00007febe7cfd000]
"TimerQueue" #49 daemon prio=5 os_prio=0 tid=0x00007feb7c204000 nid=0x6a94 waiting on condition [0x00007febe7dfe000]
"MsgDispatcher-0" #46 daemon prio=5 os_prio=0 tid=0x00007feba0031000 nid=0x6a91 waiting on condition [0x00007febec198000]
"DestroyJavaVM" #45 prio=5 os_prio=0 tid=0x00007fec24009800 nid=0x6a2c waiting on condition [0x0000000000000000]
"LoggingPlugin Timer" #43 prio=5 os_prio=0 tid=0x00007fec247dc800 nid=0x6a8d in Object.wait() [0x00007febec6ed000]
"Updater thread" #40 prio=5 os_prio=0 tid=0x00007feb9802f800 nid=0x6a8a waiting on condition [0x00007febecbf6000]
"AWT-EventQueue-0" #30 prio=6 os_prio=0 tid=0x00007fec246ee000 nid=0x6a7f waiting on condition [0x00007fec047b3000]
"AWT-Shutdown" #31 prio=5 os_prio=0 tid=0x00007fec246ed000 nid=0x6a7e in Object.wait() [0x00007fec04ab4000]
"MsgDispatcher-1" #29 daemon prio=5 os_prio=0 tid=0x00007fec246ea800 nid=0x6a7d waiting on condition [0x00007fec0c784000]
"MsgDispatcher-0" #28 daemon prio=5 os_prio=0 tid=0x00007fec246e9800 nid=0x6a7c waiting on condition [0x00007fec07dfe000]
"Updater thread" #27 prio=5 os_prio=0 tid=0x00007feb940e0000 nid=0x6a7b waiting on condition [0x00007fec07cfd000]
"Update Checker Timer" #26 prio=5 os_prio=0 tid=0x00007feb940de800 nid=0x6a7a in Object.wait() [0x00007fec0c885000]
"AWT-XAWT" #23 daemon prio=6 os_prio=0 tid=0x00007fec245e2000 nid=0x6a77 runnable [0x00007fec04bb5000]
"Java2D Disposer" #21 daemon prio=10 os_prio=0 tid=0x00007fec245b7000 nid=0x6a76 in Object.wait() [0x00007fec052c6000]
"MsgDispatcher-0" #15 daemon prio=5 os_prio=0 tid=0x00007fec24429800 nid=0x6a43 waiting on condition [0x00007fec0c371000]
"RMI TCP Accept-3634" #14 daemon prio=5 os_prio=0 tid=0x00007fec243e5000 nid=0x6a42 runnable [0x00007fec0c683000]
"RMI TCP Accept-0" #11 daemon prio=5 os_prio=0 tid=0x00007fec2437b000 nid=0x6a3f runnable [0x00007fec0c986000]
"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007fec2421c000 nid=0x6a3d runnable [0x0000000000000000]
"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007fec2420e800 nid=0x6a3c waiting on condition [0x0000000000000000]
"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007fec2420c800 nid=0x6a3b waiting on condition [0x0000000000000000]
"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007fec2420a800 nid=0x6a3a waiting on condition [0x0000000000000000]
"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007fec24208000 nid=0x6a39 waiting on condition [0x0000000000000000]
"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fec24206800 nid=0x6a38 waiting on condition [0x0000000000000000]
"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fec241d3000 nid=0x6a37 in Object.wait() [0x00007fec0da09000]
"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fec241ce000 nid=0x6a36 in Object.wait() [0x00007fec0db0a000]
"VM Thread" os_prio=0 tid=0x00007fec241c6800 nid=0x6a35 runnable
"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fec2401f000 nid=0x6a2d runnable
"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fec24020800 nid=0x6a2e runnable
"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fec24022800 nid=0x6a2f runnable
"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fec24024000 nid=0x6a30 runnable
"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007fec24026000 nid=0x6a31 runnable
"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007fec24027800 nid=0x6a32 runnable
"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007fec24029800 nid=0x6a33 runnable
"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007fec2402b000 nid=0x6a34 runnable
"VM Periodic Task Thread" os_prio=0 tid=0x00007fec24226800 nid=0x6a3e waiting on condition
```

Which all looks sensible given the freshness of the client.

**Comment by csmith** [comment]
I've never noticed a problem, and my 2-day-running client has 53 threads.

Probably a plugin you're running that I'm not? Or something weird you're doing that I'm not?

Either way, can't really debug without knowing what the threads are.

**Comment by ShaneMcC** [comment]
The first of the threads was Feb12, so this was ~5 days:

```
[19:08:11] [shane@Xion:~]$ ps -T ux | grep -i DMDirc
shane     2627  2627  0.0 10.7 19742424 1545400 pts/2 Sl+ Feb12   0:00 java -jar DMDirc.jar
```

I think it's a leak whenever the client tries to connect to a server, I tend to leave server windows lying around that don't always have something to connect to (local dev dfbnc) etc.

It looks to be about 11 threads a minute:

```
shane     2627  6411  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:50   0:00 java -jar DMDirc.jar
shane     2627  6416  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:50   0:00 java -jar DMDirc.jar
shane     2627  6443  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6449  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6454  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6458  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6465  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6472  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6476  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6481  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6485  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6496  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6502  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:51   0:00 java -jar DMDirc.jar
shane     2627  6506  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:52   0:00 java -jar DMDirc.jar
shane     2627  6519  0.0 10.7 19742424 1545400 pts/2 Sl+ 02:52   0:00 java -jar DMDirc.jar
```

Which is slightly over 5 seconds between threads which fits with the reconnect timeout:

```
«19:39:38» «Connecting» Connecting to 127.0.0.1:16667
«19:39:38» «Reconnecting» Reconnecting to 127.0.0.1 in 5 seconds
«19:39:43» «Connecting» Connecting to 127.0.0.1:16667
«19:39:43» «Reconnecting» Reconnecting to 127.0.0.1 in 5 seconds
«19:39:48» «Connecting» Connecting to 127.0.0.1:16667
«19:39:48» «Reconnecting» Reconnecting to 127.0.0.1 in 5 seconds
«19:39:53» «Connecting» Connecting to 127.0.0.1:16667
«19:39:53» «Reconnecting» Reconnecting to 127.0.0.1 in 5 seconds
```

The thread count is stable at the moment on my new client, but I've not done any dev work that will result in a endless-reconnect server since starting this client.

I can cause the thread count to grow by trying to connect to a server that isn't running for a bit.

Currently at:

```
[19:36:35] [shane@Xion:~]$ ps -T ux | grep -i DMDirc | wc -l
172
[19:41:58] [shane@Xion:~]$  
```

We look to be leaking MsgDispatcher threads:

```
[19:42:46] [shane@Xion:~]$ cat /tmp/screen-exchange | grep -i MsgDispatcher | wc -l
109
[19:42:52] [shane@Xion:~]$ 
```

**Comment by ShaneMcC** [comment]
Some of the 'dead' MsgDispatcher threads:

```
"MsgDispatcher-0" #585 daemon prio=5 os_prio=0 tid=0x00007fec244b8800 nid=0x7f13 waiting on condition [0x00007feb015d4000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000790e01f98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:66)
        at java.lang.Thread.run(Thread.java:745)

"MsgDispatcher-0" #581 daemon prio=5 os_prio=0 tid=0x00007fec244b7000 nid=0x7f05 waiting on condition [0x00007feb012d1000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000790e38d10> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:66)
        at java.lang.Thread.run(Thread.java:745)

"MsgDispatcher-0" #573 daemon prio=5 os_prio=0 tid=0x00007fec244b5000 nid=0x7eec waiting on condition [0x00007feb016d5000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000790b84928> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:66)
        at java.lang.Thread.run(Thread.java:745)

"MsgDispatcher-0" #569 daemon prio=5 os_prio=0 tid=0x00007fec244b2800 nid=0x7edd waiting on condition [0x00007feb017d6000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000790e2e7f0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:66)
        at java.lang.Thread.run(Thread.java:745)

"MsgDispatcher-0" #565 daemon prio=5 os_prio=0 tid=0x00007fec244b0800 nid=0x7ec8 waiting on condition [0x00007feb019d8000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000790b9e368> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:66)
        at java.lang.Thread.run(Thread.java:745)

"MsgDispatcher-0" #561 daemon prio=5 os_prio=0 tid=0x00007fec244af800 nid=0x7eb4 waiting on condition [0x00007feb01fde000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000790be9778> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at net.engio.mbassy.bus.AbstractSyncAsyncMessageBus$1.run(AbstractSyncAsyncMessageBus.java:66)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ShaneMcC** [comment]
[Full thread dump](https://github.com/DMDirc/DMDirc/files/784153/thread-dump.txt)

**Comment by csmith** [comment]
So this is the Parser's callback manager.

We need to call shutdown() on it when the parser is finished with. (I think that means adding a shutdown()/release() method to the parser, as well...)
